version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: tripzy-app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     # Example DB envs â€“ match what your Node app expects
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: tripzy
  #     DB_PASSWORD: tripzy
  #     DB_NAME: TripzyDB
  #   depends_on:
  #     - db
  #   networks:
  #     - backend-network

  db:
    image: postgres:latest
    container_name: tripzy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TripzyDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - backend-network

  adminer:
    image: adminer:latest
    container_name: tripzy-adminer
    ports:
      - "8080:8080" 
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
